// One lazy chunk per demo, mounted by CatalogCard when its card scrolls into
// view, so leaflet, tiptap and echarts stay out of the initial page JS.
// Keys match demoNameFor(name) in lib/ui-catalog/catalog.ts.
import { lazy, type ComponentType } from 'react'

export const DEMOS: Record<string, ComponentType> = {
  AccordionDemo: lazy(() => import('./AccordionDemo')),
  AvatarDemo: lazy(() => import('./AvatarDemo')),
  BadgeDemo: lazy(() => import('./BadgeDemo')),
  BreadcrumbDemo: lazy(() => import('./BreadcrumbDemo')),
  ButtonDemo: lazy(() => import('./ButtonDemo')),
  CalendarDemo: lazy(() => import('./CalendarDemo')),
  CardDemo: lazy(() => import('./CardDemo')),
  ChartsDemo: lazy(() => import('./ChartsDemo')),
  CheckboxDemo: lazy(() => import('./CheckboxDemo')),
  CollapsibleDemo: lazy(() => import('./CollapsibleDemo')),
  CommandDemo: lazy(() => import('./CommandDemo')),
  ContextMenuDemo: lazy(() => import('./ContextMenuDemo')),
  DataListDemo: lazy(() => import('./DataListDemo')),
  DataTableDemo: lazy(() => import('./DataTableDemo')),
  DialogDemo: lazy(() => import('./DialogDemo')),
  DropdownMenuDemo: lazy(() => import('./DropdownMenuDemo')),
  EmptyStateDemo: lazy(() => import('./EmptyStateDemo')),
  FileUploadDemo: lazy(() => import('./FileUploadDemo')),
  FormDemo: lazy(() => import('./FormDemo')),
  IconBoxDemo: lazy(() => import('./IconBoxDemo')),
  InputDemo: lazy(() => import('./InputDemo')),
  KbdDemo: lazy(() => import('./KbdDemo')),
  KpiGridDemo: lazy(() => import('./KpiGridDemo')),
  LabelDemo: lazy(() => import('./LabelDemo')),
  LeafletMapDemo: lazy(() => import('./LeafletMapDemo')),
  OverlayScrollDemo: lazy(() => import('./OverlayScrollDemo')),
  PageDemo: lazy(() => import('./PageDemo')),
  PinInputDemo: lazy(() => import('./PinInputDemo')),
  PopoverDemo: lazy(() => import('./PopoverDemo')),
  ProgressDemo: lazy(() => import('./ProgressDemo')),
  RadioGroupDemo: lazy(() => import('./RadioGroupDemo')),
  RangeCalendarDemo: lazy(() => import('./RangeCalendarDemo')),
  RichTextEditorDemo: lazy(() => import('./RichTextEditorDemo')),
  SectionCardDemo: lazy(() => import('./SectionCardDemo')),
  SelectDemo: lazy(() => import('./SelectDemo')),
  SeparatorDemo: lazy(() => import('./SeparatorDemo')),
  SheetDemo: lazy(() => import('./SheetDemo')),
  SidebarDemo: lazy(() => import('./SidebarDemo')),
  SkeletonDemo: lazy(() => import('./SkeletonDemo')),
  SliderDemo: lazy(() => import('./SliderDemo')),
  SonnerDemo: lazy(() => import('./SonnerDemo')),
  SwitchDemo: lazy(() => import('./SwitchDemo')),
  TableDemo: lazy(() => import('./TableDemo')),
  TabsDemo: lazy(() => import('./TabsDemo')),
  TextareaDemo: lazy(() => import('./TextareaDemo')),
  ThemeSwitchDemo: lazy(() => import('./ThemeSwitchDemo')),
  ToggleDemo: lazy(() => import('./ToggleDemo')),
  ToggleGroupDemo: lazy(() => import('./ToggleGroupDemo')),
  TooltipDemo: lazy(() => import('./TooltipDemo')),
}
